[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
walkmore = "3F9toSY7wmhJ13RmHrEHrpkr4CRnnV7XizWxDB4bmepx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
