[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
walkmore = "2147VBdRR2xGS6BnY8RsprPhh4MHPoApgnzqgNm2LLFu"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]